import { Order } from "../types";
import { minsAgo, hrsAgo } from "./helpers";

export const mockOrders: Order[] = [
  {
    id: "ORD-1024",
    customerId: "C-001",
    customerName: "Aisha Bello",
    customerPhone: "+234 806 123 4567",
    deliveryAddress: "12 Wurno Road, Dutse, Jigawa State",
    items: [
      { id: "F-001", name: "Jollof Rice", quantity: 1, price: 3500 },
      { id: "F-002", name: "Chicken", quantity: 1, price: 2500 },
      { id: "F-010", name: "Coca-Cola", quantity: 2, price: 500 },
    ],
    subtotal: 7000,
    deliveryFee: 1500,
    total: 8500,
    status: "on_the_way",
    riderId: "R-001",
    riderName: "Muhammad Abdullahi",
    createdAt: minsAgo(35),
    updatedAt: minsAgo(12),
    estimatedDelivery: minsAgo(-15),
    timeline: [
      { status: "pending", timestamp: minsAgo(35), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(33), label: "Confirmed" },
      { status: "preparing", timestamp: minsAgo(30), label: "Preparing" },
      { status: "ready", timestamp: minsAgo(18), label: "Ready" },
      { status: "assigned", timestamp: minsAgo(15), label: "Rider Assigned" },
      { status: "on_the_way", timestamp: minsAgo(12), label: "Picked Up" },
    ],
  },
  {
    id: "ORD-1023",
    customerId: "C-002",
    customerName: "Ibrahim Musa",
    customerPhone: "+234 807 234 5678",
    deliveryAddress: "5 Babura Road, Dutse, Jigawa State",
    items: [
      { id: "F-003", name: "Fried Rice", quantity: 1, price: 3000 },
      { id: "F-004", name: "Beef", quantity: 1, price: 2000 },
    ],
    subtotal: 5000,
    deliveryFee: 1200,
    total: 6200,
    status: "preparing",
    riderId: null,
    riderName: null,
    createdAt: minsAgo(20),
    updatedAt: minsAgo(15),
    timeline: [
      { status: "pending", timestamp: minsAgo(20), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(18), label: "Confirmed" },
      { status: "preparing", timestamp: minsAgo(15), label: "Preparing" },
    ],
  },
  {
    id: "ORD-1022",
    customerId: "C-003",
    customerName: "Maryam Yusuf",
    customerPhone: "+234 808 345 6789",
    deliveryAddress: "8 Hadejia Road, Dutse, Jigawa State",
    items: [
      { id: "F-005", name: "Chicken Shawarma", quantity: 1, price: 3500 },
      { id: "F-011", name: "Fanta", quantity: 1, price: 500 },
    ],
    subtotal: 4000,
    deliveryFee: 1000,
    total: 4500,
    status: "ready",
    riderId: "R-003",
    riderName: "Abdulrahman Musa",
    createdAt: minsAgo(50),
    updatedAt: minsAgo(5),
    timeline: [
      { status: "pending", timestamp: minsAgo(50), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(48), label: "Confirmed" },
      { status: "preparing", timestamp: minsAgo(45), label: "Preparing" },
      { status: "ready", timestamp: minsAgo(5), label: "Ready for Pickup" },
    ],
  },
  {
    id: "ORD-1021",
    customerId: "C-004",
    customerName: "Fatima Abubakar",
    customerPhone: "+234 809 456 7890",
    deliveryAddress: "3 Kiyawa Road, Dutse, Jigawa State",
    items: [
      { id: "F-006", name: "Tuwo Shinkafa", quantity: 2, price: 2000 },
      { id: "F-007", name: "Miyan Kuka", quantity: 1, price: 1500 },
    ],
    subtotal: 5500,
    deliveryFee: 1500,
    total: 7000,
    status: "assigned",
    riderId: "R-002",
    riderName: "Usman Ibrahim",
    createdAt: hrsAgo(1.5),
    updatedAt: minsAgo(25),
    timeline: [
      { status: "pending", timestamp: hrsAgo(1.5), label: "Order Placed" },
      { status: "confirmed", timestamp: hrsAgo(1.45), label: "Confirmed" },
      { status: "preparing", timestamp: hrsAgo(1.4), label: "Preparing" },
      { status: "ready", timestamp: minsAgo(30), label: "Ready" },
      { status: "assigned", timestamp: minsAgo(25), label: "Rider Assigned" },
    ],
  },
  {
    id: "ORD-1020",
    customerId: "C-005",
    customerName: "Yusuf Abdullahi",
    customerPhone: "+234 810 567 8901",
    deliveryAddress: "15 Ringim Road, Dutse, Jigawa State",
    items: [
      { id: "F-008", name: "Pounded Yam", quantity: 1, price: 2500 },
      { id: "F-009", name: "Egusi Soup", quantity: 1, price: 2000 },
      { id: "F-012", name: "Chivita", quantity: 1, price: 800 },
    ],
    subtotal: 5300,
    deliveryFee: 1500,
    total: 6800,
    status: "delivered",
    riderId: "R-004",
    riderName: "Sadiq Bello",
    createdAt: hrsAgo(2),
    updatedAt: hrsAgo(1.2),
    timeline: [
      { status: "pending", timestamp: hrsAgo(2), label: "Order Placed" },
      { status: "confirmed", timestamp: hrsAgo(1.95), label: "Confirmed" },
      { status: "preparing", timestamp: hrsAgo(1.9), label: "Preparing" },
      { status: "ready", timestamp: hrsAgo(1.5), label: "Ready" },
      { status: "assigned", timestamp: hrsAgo(1.45), label: "Rider Assigned" },
      { status: "on_the_way", timestamp: hrsAgo(1.4), label: "Picked Up" },
      { status: "delivered", timestamp: hrsAgo(1.2), label: "Delivered" },
    ],
  },
  {
    id: "ORD-1019",
    customerId: "C-006",
    customerName: "Halima Garba",
    customerPhone: "+234 811 678 9012",
    deliveryAddress: "7 Gumel Road, Dutse, Jigawa State",
    items: [
      { id: "F-001", name: "Jollof Rice", quantity: 2, price: 3500 },
      { id: "F-002", name: "Chicken", quantity: 2, price: 2500 },
    ],
    subtotal: 12000,
    deliveryFee: 2000,
    total: 14000,
    status: "delivered",
    riderId: "R-005",
    riderName: "Aminu Yusuf",
    createdAt: hrsAgo(3),
    updatedAt: hrsAgo(2.1),
    timeline: [
      { status: "pending", timestamp: hrsAgo(3), label: "Order Placed" },
      { status: "confirmed", timestamp: hrsAgo(2.95), label: "Confirmed" },
      { status: "preparing", timestamp: hrsAgo(2.9), label: "Preparing" },
      { status: "ready", timestamp: hrsAgo(2.5), label: "Ready" },
      { status: "assigned", timestamp: hrsAgo(2.45), label: "Rider Assigned" },
      { status: "on_the_way", timestamp: hrsAgo(2.4), label: "Picked Up" },
      { status: "delivered", timestamp: hrsAgo(2.1), label: "Delivered" },
    ],
  },
  {
    id: "ORD-1018",
    customerId: "C-007",
    customerName: "Umar Faruk",
    customerPhone: "+234 812 789 0123",
    deliveryAddress: "20 Birnin Kudu Road, Dutse, Jigawa State",
    items: [
      { id: "F-005", name: "Chicken Shawarma", quantity: 3, price: 3500 },
    ],
    subtotal: 10500,
    deliveryFee: 2000,
    total: 12500,
    status: "pending",
    riderId: null,
    riderName: null,
    createdAt: minsAgo(2),
    updatedAt: minsAgo(2),
    timeline: [
      { status: "pending", timestamp: minsAgo(2), label: "Order Placed" },
    ],
  },
  {
    id: "ORD-1017",
    customerId: "C-008",
    customerName: "Zainab Sani",
    customerPhone: "+234 813 890 1234",
    deliveryAddress: "4 Kazaure Road, Dutse, Jigawa State",
    items: [
      { id: "F-003", name: "Fried Rice", quantity: 1, price: 3000 },
      { id: "F-010", name: "Coca-Cola", quantity: 3, price: 500 },
    ],
    subtotal: 4500,
    deliveryFee: 1200,
    total: 5700,
    status: "confirmed",
    riderId: null,
    riderName: null,
    createdAt: minsAgo(8),
    updatedAt: minsAgo(6),
    timeline: [
      { status: "pending", timestamp: minsAgo(8), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(6), label: "Confirmed" },
    ],
  },
  {
    id: "ORD-1016",
    customerId: "C-009",
    customerName: "Aliyu Danjuma",
    customerPhone: "+234 814 901 2345",
    deliveryAddress: "11 Gwaram Road, Dutse, Jigawa State",
    items: [
      { id: "F-006", name: "Tuwo Shinkafa", quantity: 1, price: 2000 },
      { id: "F-007", name: "Miyan Kuka", quantity: 1, price: 1500 },
      { id: "F-012", name: "Chivita", quantity: 2, price: 800 },
    ],
    subtotal: 5100,
    deliveryFee: 1500,
    total: 6600,
    status: "cancelled",
    riderId: null,
    riderName: null,
    createdAt: hrsAgo(4),
    updatedAt: hrsAgo(3.75),
    timeline: [
      { status: "pending", timestamp: hrsAgo(4), label: "Order Placed" },
      { status: "cancelled", timestamp: hrsAgo(3.75), label: "Cancelled" },
    ],
  },
  {
    id: "ORD-1015",
    customerId: "C-010",
    customerName: "Rukayya Ibrahim",
    customerPhone: "+234 815 012 3456",
    deliveryAddress: "6 Jahun Road, Dutse, Jigawa State",
    items: [
      { id: "F-008", name: "Pounded Yam", quantity: 2, price: 2500 },
      { id: "F-009", name: "Egusi Soup", quantity: 2, price: 2000 },
    ],
    subtotal: 9000,
    deliveryFee: 2000,
    total: 11000,
    status: "delivered",
    riderId: "R-001",
    riderName: "Muhammad Abdullahi",
    createdAt: hrsAgo(5),
    updatedAt: hrsAgo(4),
    timeline: [
      { status: "pending", timestamp: hrsAgo(5), label: "Order Placed" },
      { status: "confirmed", timestamp: hrsAgo(4.95), label: "Confirmed" },
      { status: "preparing", timestamp: hrsAgo(4.9), label: "Preparing" },
      { status: "ready", timestamp: hrsAgo(4.5), label: "Ready" },
      { status: "assigned", timestamp: hrsAgo(4.45), label: "Rider Assigned" },
      { status: "on_the_way", timestamp: hrsAgo(4.4), label: "Picked Up" },
      { status: "delivered", timestamp: hrsAgo(4), label: "Delivered" },
    ],
  },
  {
    id: "ORD-1014",
    customerId: "C-011",
    customerName: "Ibrahim Danladi",
    customerPhone: "+234 816 123 4567",
    deliveryAddress: "9 Kafin Hausa Road, Dutse, Jigawa State",
    items: [
      { id: "F-001", name: "Jollof Rice", quantity: 1, price: 3500 },
      { id: "F-004", name: "Beef", quantity: 1, price: 2000 },
    ],
    subtotal: 5500,
    deliveryFee: 1500,
    total: 7000,
    status: "on_the_way",
    riderId: "R-003",
    riderName: "Abdulrahman Musa",
    createdAt: minsAgo(42),
    updatedAt: minsAgo(18),
    estimatedDelivery: minsAgo(-10),
    timeline: [
      { status: "pending", timestamp: minsAgo(42), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(40), label: "Confirmed" },
      { status: "preparing", timestamp: minsAgo(37), label: "Preparing" },
      { status: "ready", timestamp: minsAgo(22), label: "Ready" },
      { status: "assigned", timestamp: minsAgo(20), label: "Rider Assigned" },
      { status: "on_the_way", timestamp: minsAgo(18), label: "Picked Up" },
    ],
  },
  {
    id: "ORD-1013",
    customerId: "C-012",
    customerName: "Safiya Balarabe",
    customerPhone: "+234 817 234 5678",
    deliveryAddress: "2 Maigatari Road, Dutse, Jigawa State",
    items: [
      { id: "F-013", name: "Suya", quantity: 4, price: 1500 },
      { id: "F-011", name: "Fanta", quantity: 4, price: 500 },
    ],
    subtotal: 8000,
    deliveryFee: 2000,
    total: 10000,
    status: "ready",
    riderId: null,
    riderName: null,
    createdAt: minsAgo(28),
    updatedAt: minsAgo(3),
    timeline: [
      { status: "pending", timestamp: minsAgo(28), label: "Order Placed" },
      { status: "confirmed", timestamp: minsAgo(26), label: "Confirmed" },
      { status: "preparing", timestamp: minsAgo(23), label: "Preparing" },
      { status: "ready", timestamp: minsAgo(3), label: "Ready" },
    ],
  },
];

export const mockNotifications = [
  {
    id: "N-001",
    type: "order" as const,
    title: "New Order Received",
    message: "Order #ORD-1018 from Umar Faruk - 3x Chicken Shawarma",
    timestamp: minsAgo(2),
    read: false,
  },
  {
    id: "N-002",
    type: "delivery" as const,
    title: "Order Delivered",
    message: "Order #ORD-1020 delivered by Sadiq Bello",
    timestamp: hrsAgo(1.2),
    read: false,
  },
  {
    id: "N-003",
    type: "rider" as const,
    title: "Rider Available",
    message: "Muhammad Abdullahi is now available",
    timestamp: minsAgo(15),
    read: true,
  },
  {
    id: "N-004",
    type: "order" as const,
    title: "Order Cancelled",
    message: "Order #ORD-1016 was cancelled by customer",
    timestamp: hrsAgo(3.75),
    read: true,
  },
  {
    id: "N-005",
    type: "system" as const,
    title: "Peak Hour Alert",
    message: "High order volume detected. Consider adding more riders.",
    timestamp: hrsAgo(2),
    read: true,
  },
  {
    id: "N-006",
    type: "delivery" as const,
    title: "Delivery Completed",
    message: "Order #ORD-1015 delivered successfully",
    timestamp: hrsAgo(4),
    read: true,
  },
];
